services:
  redis:
    image: redis/redis-stack:latest
    container_name: rediscontainer
    ports:
      - "6379"
    networks:
      - backend
    volumes:
      - ./redis_data/:/data
    expose:
      - 6379

  reminder-backend:
    image: "lucasahli/reminder-backend:<IMAGE_TAG>"
    ports: # port_on_host_machine:port_on_container
      - "4000:4000" 
    env_file:
      - .env.production
    environment:
      VAULT_ADDR: http://vault:8200
    networks:
      - backend
    depends_on:
      - redis
networks:
  backend: