services:
  redis:
    image: redis/redis-stack:latest
    container_name: rediscontainer
    ports:
      - "6379"
    networks:
      - backend
    volumes:
      - ./redis_data/:/data
    expose:
      - 6379
    restart: always

  reminder-backend:
    image: "lucasahli/reminder-backend:<IMAGE_TAG>"
    ports: # port_on_host_machine:port_on_container
      - "4000:4000"
    environment:
      - FIREBASE_SERVICE_ACCOUNT_KEY=${FIREBASE_SERVICE_ACCOUNT_KEY}
      - HASH_SECRET=${HASH_SECRET}
      - API_SERVER_PORT=4000
      - REDIS_HOST=rediscontainer
      - REDIS_PORT=6379
      - NODE_OPTIONS='--experimental-vm-modules'
    networks:
      - backend
    depends_on:
      - redis
    restart: always
networks:
  backend: