services:
  express-server:
    build:
      context: . # path to Dockerfile to build
      target: buildstage # targetStage in the Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/.pnpm-store # is only here to prevent syncing with the host machine
      - /usr/src/app/node_modules # is only here to prevent syncing with the host machine (this hack works because this path is more specific than /usr/src/app)
    ports: # port_on_host_machine:port_on_container
      - 8080:8080 
      - 9229:9229 # for debugging

    command: pnpm run dev # overrides the RUN command of the targetStage in the Dockerfile