services:
  express-server:
    build:
      context: . # path to Dockerfile to build
      target: productionstage # targetStage in the Dockerfile
    ports: # port_on_host_machine:port_on_container
      - 8080:8080 
      - 9229:9229 # for debugging

    #command: pnpm run dev # overrides the RUN command of the targetStage in the Dockerfile