services:
  redis:
    image: redis/redis-stack:latest
    container_name: rediscontainer
    ports:
      - "6379"
    networks:
      - backend
    volumes:
      - ./redis_data/:/data
    expose:
      - 6379
  express-server:
    build:
      context: . # path to Dockerfile to build
      target: productionstage # targetStage in the Dockerfile
    ports: # port_on_host_machine:port_on_container
      - "4000:4000" 
    env_file:
      - .env.production
    networks:
      - backend
    depends_on:
      - redis
networks:
  backend: